name: "Install a binary from GitHub releases"
description: "Install binaries from GitHub releases"
author: "Lee Briggs"
inputs:
  repo:
    description: "GitHub repo where binary is located"
    required: true
  tag:
    description: "tag containing binary to install"
    default: latest
    required: true
  token:
    description: >
      Personal access token (PAT) used to fetch release metadata or private binaries.
    default: ${{ github.token }}
    required: true
  extractArgs:
    description: >
      Arguments for extracting release tar.
    default: |
      xz
    required: true
  arch:
    description: >
      if provided, release binaries will be matched for `<plaform>.*<arch>.*<ext>`
      else release binaries will only be matched by `<platform>.*<ext>`
branding:
  icon: 'archive'
  color: 'green'
runs:
  using: 'node12'
  main: 'lib/main.js'
