name: "Test typescript-action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  change-aws-credentials:
    strategy:
      matrix:
        runs-on: [ "ubuntu-latest", "macos-latest" ]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          repo: jaxxstorm/change-aws-credentials
          tag: v0.3.3
      - run: change-aws-credentials version
  tf2pulumi:
    strategy:
      matrix:
        version: ["v0.7.0", "v0.8.0"]
        runs-on: [ "ubuntu-latest", "macos-latest" ]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          repo: pulumi/tf2pulumi
          tag: ${{ matrix.version }}
      - run: tf2pulumi version
  tf2pulumi-latest:
    strategy:
      matrix:
        runs-on: [ "ubuntu-latest", "macos-latest" ]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          repo: pulumi/tf2pulumi
          arch: x64
      - run: tf2pulumi version
  go-cag:
    strategy:
      matrix:
        version: ["v2.0.0", "latest"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run build
      - name: Generate download token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.AUTH_FOR_BINARY_GITHUB_APP_ID }}
          private_key: ${{ secrets.AUTH_FOR_BINARY_GITHUB_APP_KEY }}
          repository: hyphengroup/go-cag
      - uses: ./
        with:
          repo: hyphengroup/go-cag
          tag: ${{ matrix.version }}
          token: ${{ steps.generate_token.outputs.token }}
      - run: cag --version
